---
title: Adnrew Fitness
timezone: GMT
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
email: naamanh10@gmail.com
mobile: 07123456789
description:
baseurl:
url:
markdown: kramdown
footerText: A short piece of text about what andrew pitter is
plugins:
  - jekyll-menus
  - jekyll-paginate
cloudinary_url: "http://res.cloudinary.com/njh101010/image/upload"
paginate: 6
paginate_path: "/blog/page/:num"
